server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taxyBooking
    username: postgres
    password: Shyam@007
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  level:
    org.springframework: INFO
#security:
#  jwt:
#    SECRET_KEY = "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437";






